# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Schnorr < Formula
  desc "Schnorr Signing (via Ristretto255) CLI tool
"
  homepage "https://github.com/aidanaden/schnorr-zig"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/aidanaden/schnorr-zig/releases/download/v0.1.0/schnorr_0.1.0_darwin_amd64.tar.gz"
      sha256 "b6a88ec4bd03fef416779cd99ca77fb97ca7c18cd9735af2f66b71ce1caad2ef"

      def install
        bin.install "schnorr"
      end
    end
    on_arm do
      url "https://github.com/aidanaden/schnorr-zig/releases/download/v0.1.0/schnorr_0.1.0_darwin_arm64.tar.gz"
      sha256 "a376809873de2f701cd19ab4c9c9dd6d37ad465fc1aa9867975863f90be636f6"

      def install
        bin.install "schnorr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aidanaden/schnorr-zig/releases/download/v0.1.0/schnorr_0.1.0_linux_amd64.tar.gz"
        sha256 "dff3a78eb8121151c36b8897621b2f84eae1d8eb58133e3a67409e117f83e0c1"

        def install
          bin.install "schnorr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aidanaden/schnorr-zig/releases/download/v0.1.0/schnorr_0.1.0_linux_arm64.tar.gz"
        sha256 "f970ad38afaa82a4f0ed165cf8b83edb1561415e2ba08f2c8624a22aef69a176"

        def install
          bin.install "schnorr"
        end
      end
    end
  end
end
