# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shamir < Formula
  desc "Shamir Secret Sharing CLI tool
"
  homepage "https://github.com/aidanaden/shamir-zig"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/aidanaden/shamir-zig/releases/download/v0.1.0/shamir_0.1.0_darwin_amd64.tar.gz"
      sha256 "564688d47919594568a034d7380448c64e68aece57ea5904f7f5988930a7e78e"

      def install
        bin.install "shamir"
      end
    end
    on_arm do
      url "https://github.com/aidanaden/shamir-zig/releases/download/v0.1.0/shamir_0.1.0_darwin_arm64.tar.gz"
      sha256 "564688d47919594568a034d7380448c64e68aece57ea5904f7f5988930a7e78e"

      def install
        bin.install "shamir"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aidanaden/shamir-zig/releases/download/v0.1.0/shamir_0.1.0_linux_amd64.tar.gz"
        sha256 "564688d47919594568a034d7380448c64e68aece57ea5904f7f5988930a7e78e"

        def install
          bin.install "shamir"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aidanaden/shamir-zig/releases/download/v0.1.0/shamir_0.1.0_linux_arm64.tar.gz"
        sha256 "77586c6a21f8d3c3a23dd76a1982f9770d11b3cc685f2cb0e7ed0cb086912234"

        def install
          bin.install "shamir"
        end
      end
    end
  end
end
