# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shamir < Formula
  desc "Shamir Secret Sharing CLI tool
"
  homepage "https://github.com/aidanaden/shamir-zig"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/aidanaden/shamir-zig/releases/download/v0.1.1/shamir_0.1.1_darwin_amd64.tar.gz"
      sha256 "bf57d0d2cc159b25a89d30d53b7403f9521ac9fa42e3ac1e9a19358f8a5807dc"

      def install
        bin.install "shamir"
      end
    end
    on_arm do
      url "https://github.com/aidanaden/shamir-zig/releases/download/v0.1.1/shamir_0.1.1_darwin_arm64.tar.gz"
      sha256 "9ad65517ccc1a5dd7106303c1fa3ee00f1df77bc95524845e58e749e4dbb2111"

      def install
        bin.install "shamir"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aidanaden/shamir-zig/releases/download/v0.1.1/shamir_0.1.1_linux_amd64.tar.gz"
        sha256 "9bcaca00e25f55c211710d3d869ec5bbc7942afcee8f36f4bdd831fb686344f8"

        def install
          bin.install "shamir"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aidanaden/shamir-zig/releases/download/v0.1.1/shamir_0.1.1_linux_arm64.tar.gz"
        sha256 "2e52785c08272dda2b4206e99cfb06fcad033225f412c771df9bba8a160dd1f4"

        def install
          bin.install "shamir"
        end
      end
    end
  end
end
